# Generated by Django 4.1.6 on 2023-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('NGO(Reg)', 'NGO(Reg'), ('NGO(Non Reg)', 'NGO(Non Reg)'), ('Social Activist/Enterpreneur', 'Social Activist/Enterpreneur'), ('Business/Manpower', 'Business/Manpower')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NonRegisterNGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('NGO(Reg)', 'NGO(Reg'), ('NGO(Non Reg)', 'NGO(Non Reg)'), ('Social Activist/Enterpreneur', 'Social Activist/Enterpreneur'), ('Business/Manpower', 'Business/Manpower')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterNGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('NGO(Reg)', 'NGO(Reg'), ('NGO(Non Reg)', 'NGO(Non Reg)'), ('Social Activist/Enterpreneur', 'Social Activist/Enterpreneur'), ('Business/Manpower', 'Business/Manpower')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SocialActivist_Enterpreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('NGO(Reg)', 'NGO(Reg'), ('NGO(Non Reg)', 'NGO(Non Reg)'), ('Social Activist/Enterpreneur', 'Social Activist/Enterpreneur'), ('Business/Manpower', 'Business/Manpower')], max_length=254)),
            ],
        ),
    ]
