# Generated by Django 4.1.6 on 2023-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate_Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Student/Intern', 'Student/Intern'), ('Advocate/Lawyer', 'Advocate/Lawyer'), ('Consumer/User', 'Consumer/User'), ('Content PublishingUpload', 'Content PublishingUpload')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Student/Intern', 'Student/Intern'), ('Advocate/Lawyer', 'Advocate/Lawyer'), ('Consumer/User', 'Consumer/User'), ('Content PublishingUpload', 'Content PublishingUpload')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Content_PublishingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Student/Intern', 'Student/Intern'), ('Advocate/Lawyer', 'Advocate/Lawyer'), ('Consumer/User', 'Consumer/User'), ('Content PublishingUpload', 'Content PublishingUpload')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Student/Intern', 'Student/Intern'), ('Advocate/Lawyer', 'Advocate/Lawyer'), ('Consumer/User', 'Consumer/User'), ('Content PublishingUpload', 'Content PublishingUpload')], max_length=254)),
            ],
        ),
    ]
