# Generated by Django 4.1.4 on 2022-12-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsel_For_Academic_And_Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ngo',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
