# Generated by Django 4.1.4 on 2022-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsel_For_Academic_And_Job', '0006_contentpublisher_professional_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpublisher',
            name='subproject',
            field=models.CharField(choices=[('student/parents', 'student/parents'), ('trainer/counsellor', 'trainer/counsellor'), ('professional/employee', 'professional/employee'), ('content publisher', 'content publisher')], max_length=254),
        ),
    ]
