# Generated by Django 4.1.4 on 2022-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counsel_For_Academic_And_Job', '0007_alter_contentpublisher_subproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional_employee',
            name='subproject',
            field=models.CharField(choices=[('student/parents', 'student/parents'), ('trainer/counsellor', 'trainer/counsellor'), ('professional/employee', 'professional/employee'), ('content publisher', 'content publisher')], max_length=254),
        ),
        migrations.AlterField(
            model_name='trainer_counsellor',
            name='subproject',
            field=models.CharField(choices=[('student/parents', 'student/parents'), ('trainer/counsellor', 'trainer/counsellor'), ('professional/employee', 'professional/employee'), ('content publisher', 'content publisher')], max_length=254),
        ),
    ]
