# Generated by Django 4.1.4 on 2023-01-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Counsel_For_Academic_And_Job', '0008_alter_professional_employee_subproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpublisher',
            name='subproject',
        ),
        migrations.RemoveField(
            model_name='professional_employee',
            name='subproject',
        ),
        migrations.RemoveField(
            model_name='trainer_counsellor',
            name='subproject',
        ),
    ]
