# Generated by Django 4.1.6 on 2023-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Organisation/Firm/Franchise', 'Organisation/Firm/Franchise'), ('Intern/Jokeer Student', 'Intern/Jokeer Student'), ('Startup/Interpreneur', 'Startup/Interpreneur'), ('Consultant/BDM', 'Consultant/BDM')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Intern_JobkeerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Organisation/Firm/Franchise', 'Organisation/Firm/Franchise'), ('Intern/Jokeer Student', 'Intern/Jokeer Student'), ('Startup/Interpreneur', 'Startup/Interpreneur'), ('Consultant/BDM', 'Consultant/BDM')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Organisation/Firm/Franchise', 'Organisation/Firm/Franchise'), ('Intern/Jokeer Student', 'Intern/Jokeer Student'), ('Startup/Interpreneur', 'Startup/Interpreneur'), ('Consultant/BDM', 'Consultant/BDM')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=254)),
                ('subproject', models.CharField(choices=[('Organisation/Firm/Franchise', 'Organisation/Firm/Franchise'), ('Intern/Jokeer Student', 'Intern/Jokeer Student'), ('Startup/Interpreneur', 'Startup/Interpreneur'), ('Consultant/BDM', 'Consultant/BDM')], max_length=254)),
            ],
        ),
    ]
